### ISSUE TITLE
Problem loading fonts

### ISSUE THREAD

**Issue by aromot** [electron-userland/electron-webpack#163]
Hello,

I can't use @font-face custom fonts.

I've modified webpack config, here's my `package.json` file:

```json
...
"electronWebpack": {
    "renderer": {
      "webpackConfig": "webpack.renderer.additions.js"
    }
  }
...
```

and accordingly, my `webpack.renderer.additions.js` file:

```javascript
module.exports = {
    module: {
        rules: [
            {
                test: /\.css$/,
                use: ['css-loader']
            },
            {
                test: /\.hbs$/,
                use: ['handlebars-loader']
            },
            {
                test: /\.less$/,
                use: ['less-loader']
            },
            {
                test: /\.(woff|woff2|eot|ttf|otf)$/,
                use: ['file-loader']
            }
        ]
    }
};
```
in my `src/renderer/index.js`, I include my `.less` file:

```javascript
...
require('../less/fonts.less');
...

```

and here's my `src/less/font.less` file:

```css
@font-face {
  font-family: 'SegoePrint';
  src:  url('../fonts/segoepr.eot') format('embedded-opentype'),
        url('../fonts/segoepr.woff') format('woff'),
        url('../fonts/segoepr.ttf') format('truetype');
  font-weight: normal;
  font-style: normal;
}
```
All the fonts files are in `src/fonts/`.

Compilation works fine but here's the error I get in the dev-tool console on runtime:

```
Failed to decode downloaded font: data:application/font-woff;base64,bW9kdWxlLmV4cG9ydHMgPSBfX3dlYnBhY2tfcHVibGljX3BhdGhfXyArICJiYzRmZmUxYjc2MDA5ZDYxMjFiNGJmN2RiMzQ1ZGI1Yy53b2ZmIjs
OTS parsing error: invalid version tag
localhost/:1 Failed to decode downloaded font: data:font/ttf;base64,bW9kdWxlLmV4cG9ydHMgPSBfX3dlYnBhY2tfcHVibGljX3BhdGhfXyArICJjNDU1ZDk0ZWVlNDNkYzRjZWViODNjMGMwZmQwZDRjOC50dGYiOw==
localhost/:1 OTS parsing error: invalid version tag
```

and of course, the text in my HTML file isn't displayed properly, I mean the SegoePrint font isn't applied as I have `font: bold 27px SegoePrint;`

I've been searching but I can't a solution. I hope I was clear enough. Any help?
