### ISSUE TITLE
Documentation should specify how to exclude files from build

### ISSUE THREAD

**Issue by kingpalethe** [electron-userland/electron-webpack#215]
Here in the documentation there is a brief discussion of using `electron-builder`.

https://webpack.electron.build/building

Near the end of this documentation, we see: `Further configurations can be made in accordance to electron-builder's documentation`.

In my case, I am trying to use `electron-builder`'s  `files` functionality to exclude certain node modules from the build. 

`electron-builder`'s documentation on this can be found here:
https://www.electron.build/configuration/contents

As a test, I am attempting to exclude one file from one node module. Here is the `build` section of my `package.json`
```
  "build": {
    "files": [
      "!node_modules/ffprobe-static/bin/win32/ia32/ffprobe.exe"
    ],
    "asarUnpack": [
      "**/app/node_modules/ffmpeg-static/*",
      "**/app/node_modules/ffprobe-static/*",
      "screenShotLib"
    ],
    "asar": true
  },
```

So you can see here that I am attempting to exclude `node_modules/ffprobe-static/bin/win32/ia32/ffprobe.exe` from the build.

After adding this, I run `yarn dist`. On the command line, I see this output.

```
electron-builder version=20.28.1
loaded configuration file=package.json ("build" field)
loaded parent configuration file=C:\Users\username\workspace\grabber\node_modules\electron-webpack\electron-builder.yml
writing effective config file=dist\builder-effective-config.yaml
```

This looks good so far, it seems that `electron-webpack`'s parent configuration was loaded, and an "effective config" is loaded.

This `effective config` does not seem to appear in the documentation, but I am assuming it is some kind of merge of my config in `package.json` and electron-builder's "parent configuration".

So now I look in my `dist` folder, and I **do find** that my `files` configuration has been written into the `builder-effective-config.yml` file 

```
---- /dist/builder-effective-config.yaml 
directories:
  output: dist
  buildResources: build
extraMetadata:
  main: main.js
files:
  - from: .
    filter:
      - package.json
      - '!node_modules/ffprobe-static/bin/win32/ia32/ffprobe.exe'
  - from: dist/main
  - from: dist/renderer
  - from: dist/renderer-dll
extraResources:
  - from: static
    to: static
asarUnpack:
  - '**/app/node_modules/ffmpeg-static/*'
  - '**/app/node_modules/ffprobe-static/*'
  - screenShotLib
asar: true
extends: electron-webpack/electron-builder.yml
electronVersion: 2.0.7
```

So you can see above that  `'!node_modules/ffprobe-static/bin/win32/ia32/ffprobe.exe'` has been written into this `builder-effective-config.yaml `

Unfortunately, after this, I find that the file still exists in this folder
`\dist\win-unpacked\resources\app.asar.unpacked\node_modules\ffprobe-static\bin\win32\ia32`

![capture](https://user-images.githubusercontent.com/11775831/47731855-391cfd00-dc22-11e8-8dbe-e78e39635278.PNG)
