### ISSUE TITLE
Not excluding files

### ISSUE THREAD

**Issue by douglassllc** [electron-userland/electron-webpack#218]
Before including electron-webpack into my build process, electron-builder was excluding the files based on the file patterns in my package.json.  Now that I am running electron-webpack prior to running electron-builder, I can see the requested excluded files/directories in my app.asar file. 

Here is my package.json.  The files I exclude in the mac section are properly excluded.  However, the files I have configured to exclude in the build files section are not being observed.  I would conclude that this is a electron-build issue, however this was working prior to me including the electron-webpack into my build:mac script.

[package.json](https://github.com/electron-userland/electron-webpack/files/2539298/test.txt)

Is there a better way for me to exclude these files/directories from the app.asar.  Since I am building for all three platforms (mac, linux, windows) I prefer not to repeat the exclusions in each platform specific build section.

**Comment by develar** [comment]
Duplicates #215

**Comment by develar** [comment]
Please try electron-builder `20.31.1`.

**Comment by douglassllc** [comment]
@develar this did not resolve the issue.  I am still seeing my private directory in the app.asar.  Maybe I have missed a configuration.

At quick glance, the duplicate issue #215 seems to be having issues with the exclude on the files property under the specific platform in the build section.  My issue is with the top level files property under the build section.

Here is some of the relevant output from running DEBUG=electron-builder using version 20.31.1
 ```
effective config config=
                       directories:
                         output: dist
                         buildResources: src/assets
                       extraMetadata:
                         main: main.js
                       files:
                         - from: .
                           filter:
                             - package.json
                             - '**/*'
                             - '!webpack*'
                             - '!.*'
                             - '!config/jsdoc.json'
                             - '!package.*'
                             - '!docs'
                             - '!private'
                         - from: dist/main
                         - from: dist/renderer
                         - from: dist/renderer-dll
                       extraResources:
                         - from: src/assets
                           to: assets
                           filter:
                             - '!track*'
                             - '!css'
```
As can be seen above.  I am filtering the private directory, but it is showing up in the app.asar.

I am probably missing config option.  Any additional guidance is appreciated.
